version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: konis_caffee
    ports:
      - "5433:5432" # Внешний порт 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d konis_caffee"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "sh", "-c", "sleep 5 && migrate -path=/migrations -database postgres://postgres:123@postgres:5432/konis_caffee?sslmode=disable up" ]
    depends_on:
      - postgres

volumes:
  db-data:
